version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install --upgrade awscli
      - >-
        sam package --template-file template.yaml --s3-bucket
        tosur-sam-cd --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
